name: On push build and push to gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      
    - run: npm install
    - run: npm run build
      
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.10
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
